defaults:
  - agent: mdp_mm_goal
  - override hydra/launcher: submitit_local
  - _self_

# task settings
task: cheetah_run
discount: 0.99
#eval
num_eval_episodes: 100
eval_every_steps: 10000
# snapshot
snapshot_ts: 300000 # 300k from paper 
snapshot_base_dir: /home/bmancilla/archive/MaskDP/maskdp_snapshots/2268
# dataset
batch_size: ${agent.batch_size}

# goal loader dataset
goal_buffer_dir: /home/bmancilla/archive/maskdp_data/maskdp_eval/expert
goal_buffer_size: 100000000
goal_buffer_num_workers: 4

# misc
seed: 3
device: cuda
save_video: true
use_tb: true
use_wandb: true
project: maskdp-mm-eval
notes: "eval single-task single-goal for mm"
replan: true


hydra:
  run:
    dir: /home/bmancilla/scratch/maskdp_eval/${task}/seed_${seed}/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}