defaults:
  - pretrain_full
  - _self_

experiment: "placeholder"
exp_name: "placeholder"
wandb_entity: "benjamin-mancilla-universidad-de-chile"
project: maskdp-mm
resume: false
resume_step: 0
finetune_from: null
copy_metrics_from: null
num_grad_steps: 200000

agent:
  freeze_schedule: {}
  lr: 1e-4
  warmup_steps: 0