defaults:
  - agent: mdp_vd4rl
  - override hydra/launcher: submitit_local
  - _self_

# task settings
task: cheetah_run
discount: 0.99

# Split configuration
train_file_split: "train"
eval_file_split: "eval"
train_ratio: 0.8
eval_ratio: 0.1
bc_ratio: 0.1

# train settings
num_grad_steps: 100010
log_every_steps: 100

# eval
eval_every_steps: 25000

# snapshot
# snapshots: [0, 25000, 50000, 75000, 100000,
#   125000, 150000, 175000, 200000, 225000, 250000, 275000, 300000,
#   325000, 350000, 375000, 400000]
snapshots: [0, 5000, 10000, 15000, 20000, 40000, 60000, 80000, 100000]
snapshot_dir: /home/bmancilla/archive/MaskDP/maskdp_snapshots_vd4rl/

# resume
resume: false
resume_dir: none
resume_step: 0

use_raw_replay_dir: true
replay_buffer_dir: /home/bmancilla/archive/MaskDP/v_d4rl_data/main/cheetah_run/expert/64px
replay_buffer_size: 500000
replay_buffer_num_workers: 8
batch_size: ${agent.batch_size}

# goal eval — desactivado para V-D4RL (sin physics)
goal_buffer_dir: null
goal_buffer_size: 50000
goal_buffer_num_workers: 4
num_goal_eval_episodes: 20

# return eval
eval_T_cond: 16
eval_T_pred: 48
eval_replan_freq: 48
num_eval_episodes: 10

# Pixel Observation
obs_type: pixels
pixel_size: 64

# Miscelaneous
seed: 1
device: cuda
save_video: false
use_tb: true
use_wandb: true
project: maskdp-mm-vd4rl
notes: "pretrain paper vd4rl pixels cheetah"
exp_name: paper_vd4rl_scratch