defaults:
  - agent: mdp
  - override hydra/launcher: submitit_local
  - _self_

# task settings
task: cheetah_run
discount: 0.99

# train settings
num_grad_steps: 400010
log_every_steps: 1000

# eval
eval_every_steps: 25000
num_eval_episodes: 10

# snapshot
snapshots: [0, 50000, 100000, 125000, 150000, 175000, 200000, 225000, 250000, 300000, 350000, 400000, 450000, 500000, 550000, 600000]
snapshot_dir: /home/bmancilla/archive/maskdp_snapshots

# resume
resume: false
resume_dir: none
resume_step: 0

# dataset TRAIN
replay_buffer_dir: /home/bmancilla/archive/maskdp_data/maskdp_train
replay_buffer_size: 2000000
replay_buffer_num_workers: 16
batch_size: ${agent.batch_size}

# dataset GOAL EVALUATION
goal_buffer_dir: /home/bmancilla/archive/MaskDP/maskdp_data/maskdp_eval/expert
goal_buffer_size: 100000
goal_buffer_num_workers: 4
num_goal_eval_episodes: 20

# Surgery settings
load_unimodal: true
pretrained_state_path: "/home/bmancilla/archive/MaskDP/maskdp_snapshots/weights/unimodal/state/snapshot_100000.pt"
pretrained_action_path: "/home/bmancilla/archive/MaskDP/maskdp_snapshots/weights/unimodal/action/snapshot_100000.pt"

# Miscelaneous
seed: 1
device: cuda
save_video: false
use_tb: true
use_wandb: true
project: maskdp-mm
notes: "pretrain-full cheetah mm"
exp_name: fase2_multimodal_cross_freeze

hydra:
  run:
    dir: /home/bmancilla/scratch/maskdp_runs/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}
