# @package agent
_target_: agent.mdp.MaskedDPMultimodalAgent
name: mdp_multimodal
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
use_tb: ${use_tb}
batch_size: 384 # Batch size Table 2
mask_ratio: [0.15, 0.35, 0.55, 0.75, 0.95]
transformer_cfg:
  # Hparams from paper (Table 2)
  traj_length: 64             # context length
  n_embd: 256                 # hidden dim
  n_head: 4                   # attention heads
  n_enc_layer: 2              # encoder layers
  n_dec_layer: 2              # decoder layers

  n_fuse_layer: 1             # fusion encoder layers
  use_fusion_type_embed: true # use fusion encoder bool (is optional)
  fusion_type: 'cross'        # 'self' | 'cross' | 'none' # fusion encoder type

  modality_dropout: true      # use modality dropout bool
  modality_dropout_prob: 0.25 # modality dropout prob
  state_dropout_prob:  0.0    # state dropout prob (if modality dropout is used)
  action_dropout_prob: 1.0    # action dropout prob (if modality dropout is used)

  # This stays the same
  embd_pdrop: 0
  resid_pdrop: 0
  attn_pdrop: 0
  pe: 'fixed'
  loss: 'total'
  norm: 'l2'

train_mode: 'joint'           # 'joint' | 'state_only' | 'action_only'

#freeze_schedule: {}

freeze_schedule:
  state_encoder_blocks:  [0, 40000000]
  action_encoder_blocks: [0, 40000000]
  # fusion_blocks:         [0     , 200000]
  # decoder_blocks:        [0     , 150000]